const emojis = {
  featured: [
    {
      name: 'grinning_face',
      image: '😀',
      codePoint: 'U+1F600',
      shortCode: ':grinning:',
    },
    {
      name: 'grinning_face_with_smile_eyes',
      image: '😄',
      codePoint: 'U+1F604',
      shortCode: ':smile:',
    },
    {
      name: 'winking_face',
      image: '😉',
      codePoint: 'U+1F614',
      shortCode: '',
      tags: 'face, wink, winking face',
    },
    {
      name: 'pensive_face',
      image: '😔',
      codePoint: 'U+1F614',
      shortCode: ':pensive:',
      tags: 'dejected, face, pensive, pensive face',
    },
    {
      name: 'confused_face',
      image: '😕',
      codePoint: 'U+1F615',
      shortCode: ':confused:',
      tags: 'confused, confused face, face',
    },
    {
      name: 'pouting_face',
      image: '😡',
      codePoint: 'U+1F621',
      shortCode: ':rage:',
      tags: 'angry, face, mad, pouting, pouting face, rage, red',
    },
    {
      name: 'grimacing_face',
      image: '😬',
      codePoint: 'U+1F62C',
      shortCode: ':grimacing:',
      tags: 'face, grimace, grimacing face',
    },
    {
      name: 'thinking_face',
      image: '🤔',
      codePoint: 'U+1F914',
      tags: 'face, thinking, thinking face',
    },
    {
      name: 'face_with_open_mouth',
      image: '😮',
      codePoint: 'U+1F62E',
      shortCode: ':open_mouth:',
      tags: 'face, face with open mouth, mouth, open, sympathy',
    },
    {
      name: 'nerd_face',
      image: '🤓',
      codePoint: 'U+1F913',
      tags: 'face, geek, nerd, nerd face',
    },
    {
      name: 'smiling_face_with_glasses',
      image: '😎',
      codePoint: 'U+1F60E',
      shortCode: ':sunglasses:',
      tags: 'bright, cool, eye, eyewear, face, glasses, smile, smiling face with sunglasses, sun, sunglasses',
    },
    {
      name: 'star_struck',
      image: '🤩',
      codePoint: 'U+1F929',
      tags: 'eyes, face, grinning, star, star-struck',
    },
    {
      name: 'smiling_face_with_halo',
      image: '😇',
      codePoint: 'U+1F607',
      shortCode: ':innocent:',
      tags: 'angel, face, fairy tale, fantasy, halo, innocent, smile, smiling face with halo',
    },
    {
      name: 'face_with_tears_of_joy',
      image: '😂',
      codePoint: 'U+1F602',
      shortCode: ':joy:',
      tags: 'face, face with tears of joy, joy, laugh, tear',
    },
    {
      name: 'zipper_mouth_face',
      image: '🤐',
      codePoint: 'U+1F910',
      tags: 'face, mouth, zipper, zipper-mouth face',
    },
    {
      name: 'skull',
      image: '💀',
      codePoint: 'U+1F480',
      shortCode: ':skull:',
      tags: 'death, face, fairy tale, monster, skull',
    },
    {
      name: 'robot_face',
      image: '🤖',
      codePoint: 'U+1F916',
      tags: 'face, monster, robot, robot face',
    },
    {
      name: 'pile_of_poo',
      image: '💩',
      codePoint: 'U+1F4A9',
      shortCode: ':hankey:, :poop:, :shit:',
      tags: 'comic, dung, face, monster, pile of poo, poo, poop',
    },
    {
      name: 'thumb_up',
      image: '👍',
      codePoint: 'U+1F44D',
      shortCode: ':+1:, :thumbsup:',
      tags: '+1, hand, thumb, thumbs up, up',
    },
    {
      name: 'thumb_down',
      image: '👎',
      codePoint: 'U+1F44E',
      shortCode: ':-1:, :thumbsdown:',
      tags: '-1, down, hand, thumb, thumbs down',
    },
    {
      name: 'clapping_hands',
      image: '👏',
      codePoint: 'U+1F44F',
      shortCode: ':clap:',
      tags: 'clap, clapping hands, hand',
    },
    {
      name: 'ok_hand',
      image: '👌',
      codePoint: 'U+1F44C',
      shortCode: ':ok_hand:',
      tags: 'hand, OK, OK hand',
    },
    {
      name: 'white_check_mark',
      image: '✅',
      codePoint: 'U+2705',
      shortCode: ':white_check_mark:',
      tags: 'check, mark, white heavy check mark',
    },
    {
      name: 'cross_mark',
      image: '❌',
      codePoint: 'U+274C',
      shortCode: ':x:',
      tags: 'cancel, cross mark, mark, multiplication, multiply, x',
    },
    {
      name: 'question_mark',
      image: '❓',
      codePoint: 'U+2753',
      shortCode: ':question:',
      tags: 'mark, punctuation, question, question mark',
    },
    {
      name: 'red_heart',
      image: '❤️',
      codePoint: 'U+2764',
      shortCode: ':heart:',
      tags: 'heart, red heart',
    },
    {
      name: 'hundred_points',
      image: '💯',
      codePoint: 'U+1F4AF',
      shortCode: ':100:',
      tags: '100, full, hundred, hundred points, score',
    },
    {
      name: 'party_popper',
      image: '🎉',
      codePoint: 'U+1F389',
      shortCode: ':tada:',
      tags: 'celebration, party, party popper, popper, tada',
    },
    {
      name: 'alarm_clock',
      image: '⏰',
      codePoint: 'U+23F0',
      shortCode: ':alarm_clock:',
      tags: 'alarm, alarm clock, clock',
    },
    {
      name: 'rocket',
      image: '🚀',
      codePoint: 'U+1F680',
      shortCode: ':rocket:',
      tags: 'rocket, space',
    },
    {
      name: '1st_place_medal',
      image: '🥇',
      codePoint: 'U+1F947',
      tags: '1st place medal, first, gold, medal',
    },
    {
      name: 'birthday_cake',
      image: '🎂',
      codePoint: 'U+1F382',
      shortCode: ':birthday:',
      tags: 'birthday, birthday cake, cake, celebration, dessert, pastry, sweet',
    },
  ],
};

export default emojis;
